# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AAACOMP iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AAACOMP iOS
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'ReachabilitySwift'
  pod 'Alamofire'
  pod 'Blueprints'
  pod 'IQKeyboardManager' 
  pod 'Kingfisher'
  pod 'SDWebImage'
  pod 'M13Checkbox'
  target 'AAACOMP iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AAACOMP iOSUITests' do
    # Pods for testing
  end

end
